language: c

dist: xenial

matrix:
  include:
    - os: linux
      addons:
        sonarcloud:
          organization: "katajakasa-github"
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - gcc-8
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      cache:
        directories:
          - '$HOME/.sonar/cache'
      after_script:
        - build-wrapper-linux-x86-64 --out-dir bw-output make
        - sonar-scanner
      env:
        - MATRIX_EVAL="CC=gcc-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - gcc-9
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=gcc-9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - clang-7
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=clang-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - clang-8
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=clang-8"

    # Power jobs

    - os: linux
      arch: ppc64le
      addons:
        sonarcloud:
          organization: "katajakasa-github"
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - gcc-8
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      cache:
        directories:
          - '$HOME/.sonar/cache'
      after_script:
        - build-wrapper-linux-x86-64 --out-dir bw-output make
        - sonar-scanner
      env:
        - MATRIX_EVAL="CC=gcc-8"
    - os: linux
      arch: ppc64le
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - gcc-9
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=gcc-9"
    - os: linux
      arch: ppc64le
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - clang-7
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=clang-7"
    - os: linux
      arch: ppc64le
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:jonathonf/ffmpeg-4'
            - sourceline: 'ppa:litenstein/sdl2-xenial'
          packages:
            - clang-8
            - cmake
            - cmake-data
            - libass-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libswscale-dev
            - libavutil-dev
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CC=clang-8"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cd $TRAVIS_BUILD_DIR
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=On .
  - make
  - make clean

notifications:
  email: false
